optimisticRepeatInstall: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320
packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.1
  better-auth: ^1.4.18
  dotenv: ^17.3.1
  effect: ^3.19.18
  hono: ^0.0.0
  react-router: ^0.0.0
  typescript: ^5.9.3
  zod: ^4.3.6
