optimisticRepeatInstall: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320
packages:
  - apps/*
  - packages/*
  - server

catalog:
  '@types/node': ^24.10.1
  better-auth: ^1.5.1
  dotenv: ^17.3.1
  effect: ^3.19.19
  hono: ^4.12.3
  react-router: ^7.13.1
  typescript: ^5.9.3
  vite: 8.0.0-beta.16
  vite-tsconfig-paths: ^6.1.1
  zod: ^4.3.6
